FROM python:3.9-alpine3.13

WORKDIR /home/appuser/app

RUN addgroup -S appgroup \
    && adduser -S -D -G appgroup appuser \
    && chown -R appuser:appgroup /home/appuser/app

USER appuser

COPY --chown=appuser:appgroup requirements.txt ./

RUN python -m venv .venv \
    && ./.venv/bin/pip install --no-cache-dir -r requirements.txt

COPY --chown=appuser:appgroup . .

CMD ["./.venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
