FROM python:3.9-alpine3.13

WORKDIR /home/appuser/app

RUN addgroup -S appgroup \
    && adduser -S -D -G appgroup appuser \
    && chown -R appuser:appgroup /home/appuser/app

USER appuser

COPY --chown=appuser:appgroup requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=appuser:appgroup . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
