# Generated by Django 4.2.7 on 2023-11-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=150, verbose_name='nick name')),
                ('role', models.CharField(choices=[('ONR', members.models.GroupRoomRole['OWNER']), ('MGR', members.models.GroupRoomRole['MANAGER']), ('MBR', members.models.GroupRoomRole['MEMBER'])], default='GroupRoomRole.MEMBER', max_length=3, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_seen_message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_messages.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.grouproom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GroupRoomMember',
                'verbose_name_plural': 'GroupRoomMembers',
            },
        ),
        migrations.CreateModel(
            name='DmRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=150, verbose_name='nick name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_seen_message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_messages.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DmRoomMember',
                'verbose_name_plural': 'DmRoomMembers',
            },
        ),
    ]
